//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MQS.TasksService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TaskInfo : object
    {
        
        private short ProgressPercentageField;
        
        private MQS.TasksService.TaskStatus StatusField;
        
        private System.Guid TaskIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ProgressPercentage
        {
            get
            {
                return this.ProgressPercentageField;
            }
            set
            {
                this.ProgressPercentageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.TaskStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TaskId
        {
            get
            {
                return this.TaskIdField;
            }
            set
            {
                this.TaskIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskStatus", Namespace="http://kilgray.com/memoqservices/2007")]
    public enum TaskStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidTask = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Executing = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnexpectedFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class UnexpectedFault : object
    {
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class GenericFault : object
    {
        
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.StatisticsTaskResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.PostTranslationAnalysisTaskResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.ConfirmAndUpdateTaskResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.XTranslateTaskResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.RunQATaskResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.PreTranslateTaskResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.TBXExportTaskResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.TBXImportTaskResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.CreateQTermTBFromTBXTaskResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.CSVImportIntoExistingTaskResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.CSVExportTaskResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.FuzzyEditDistanceTaskResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.LevenshteinEditDistanceTaskResult))]
    public partial class TaskResult : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatisticsTaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class StatisticsTaskResult : MQS.TasksService.TaskResult
    {
        
        private System.Nullable<System.Guid> AnalysisReportIdField;
        
        private MQS.TasksService.StatisticsResultForLang[] ResultsForTargetLangsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> AnalysisReportId
        {
            get
            {
                return this.AnalysisReportIdField;
            }
            set
            {
                this.AnalysisReportIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.StatisticsResultForLang[] ResultsForTargetLangs
        {
            get
            {
                return this.ResultsForTargetLangsField;
            }
            set
            {
                this.ResultsForTargetLangsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTranslationAnalysisTaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class PostTranslationAnalysisTaskResult : MQS.TasksService.TaskResult
    {
        
        private System.Nullable<System.Guid> PTAReportIdField;
        
        private MQS.TasksService.PostTranslationResultForLang[] ResultsForTargetLangsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PTAReportId
        {
            get
            {
                return this.PTAReportIdField;
            }
            set
            {
                this.PTAReportIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTranslationResultForLang[] ResultsForTargetLangs
        {
            get
            {
                return this.ResultsForTargetLangsField;
            }
            set
            {
                this.ResultsForTargetLangsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmAndUpdateTaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class ConfirmAndUpdateTaskResult : MQS.TasksService.TaskResult
    {
        
        private MQS.TasksService.ConfirmAndUpdateDocError[] DocErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.ConfirmAndUpdateDocError[] DocErrors
        {
            get
            {
                return this.DocErrorsField;
            }
            set
            {
                this.DocErrorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XTranslateTaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class XTranslateTaskResult : MQS.TasksService.TaskResult
    {
        
        private MQS.TasksService.XTranslateDocumentResult[] DocumentResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.XTranslateDocumentResult[] DocumentResults
        {
            get
            {
                return this.DocumentResultsField;
            }
            set
            {
                this.DocumentResultsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RunQATaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class RunQATaskResult : MQS.TasksService.TaskResult
    {
        
        private MQS.TasksService.QAReport ReportField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.QAReport Report
        {
            get
            {
                return this.ReportField;
            }
            set
            {
                this.ReportField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreTranslateTaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class PreTranslateTaskResult : MQS.TasksService.TaskResult
    {
        
        private MQS.TasksService.PreTranslateProblem[] ProblemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PreTranslateProblem[] Problems
        {
            get
            {
                return this.ProblemsField;
            }
            set
            {
                this.ProblemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBXExportTaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TBXExportTaskResult : MQS.TasksService.TaskResult
    {
        
        private string ErrorMessageField;
        
        private System.Guid ExportedFileIdField;
        
        private System.Guid LogFileIdField;
        
        private string[] WarningsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ExportedFileId
        {
            get
            {
                return this.ExportedFileIdField;
            }
            set
            {
                this.ExportedFileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LogFileId
        {
            get
            {
                return this.LogFileIdField;
            }
            set
            {
                this.LogFileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Warnings
        {
            get
            {
                return this.WarningsField;
            }
            set
            {
                this.WarningsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBXImportTaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.CreateQTermTBFromTBXTaskResult))]
    public partial class TBXImportTaskResult : MQS.TasksService.TaskResult
    {
        
        private string ErrorMessageField;
        
        private System.Guid LogFileIdField;
        
        private string[] RemovedFilterNamesField;
        
        private MQS.TasksService.TBXImportResults ResultTypeField;
        
        private string[] WarningsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LogFileId
        {
            get
            {
                return this.LogFileIdField;
            }
            set
            {
                this.LogFileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] RemovedFilterNames
        {
            get
            {
                return this.RemovedFilterNamesField;
            }
            set
            {
                this.RemovedFilterNamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.TBXImportResults ResultType
        {
            get
            {
                return this.ResultTypeField;
            }
            set
            {
                this.ResultTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Warnings
        {
            get
            {
                return this.WarningsField;
            }
            set
            {
                this.WarningsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateQTermTBFromTBXTaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class CreateQTermTBFromTBXTaskResult : MQS.TasksService.TBXImportTaskResult
    {
        
        private System.Guid CreatedTBGuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedTBGuid
        {
            get
            {
                return this.CreatedTBGuidField;
            }
            set
            {
                this.CreatedTBGuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSVImportIntoExistingTaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class CSVImportIntoExistingTaskResult : MQS.TasksService.TaskResult
    {
        
        private int EntryNumField;
        
        private int EntryWithErrorNumField;
        
        private string ErrorMessageField;
        
        private int FailedToImportEntryNumField;
        
        private int ImportedEntryNumField;
        
        private int NumberOfErrorsField;
        
        private int NumberOfWarningsField;
        
        private System.Guid ReportFileIdField;
        
        private int RowNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EntryNum
        {
            get
            {
                return this.EntryNumField;
            }
            set
            {
                this.EntryNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EntryWithErrorNum
        {
            get
            {
                return this.EntryWithErrorNumField;
            }
            set
            {
                this.EntryWithErrorNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FailedToImportEntryNum
        {
            get
            {
                return this.FailedToImportEntryNumField;
            }
            set
            {
                this.FailedToImportEntryNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImportedEntryNum
        {
            get
            {
                return this.ImportedEntryNumField;
            }
            set
            {
                this.ImportedEntryNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfErrors
        {
            get
            {
                return this.NumberOfErrorsField;
            }
            set
            {
                this.NumberOfErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfWarnings
        {
            get
            {
                return this.NumberOfWarningsField;
            }
            set
            {
                this.NumberOfWarningsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReportFileId
        {
            get
            {
                return this.ReportFileIdField;
            }
            set
            {
                this.ReportFileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNum
        {
            get
            {
                return this.RowNumField;
            }
            set
            {
                this.RowNumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSVExportTaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class CSVExportTaskResult : MQS.TasksService.TaskResult
    {
        
        private string ErrorMessageField;
        
        private System.Guid ExportedFileIdField;
        
        private string[] WarningsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ExportedFileId
        {
            get
            {
                return this.ExportedFileIdField;
            }
            set
            {
                this.ExportedFileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Warnings
        {
            get
            {
                return this.WarningsField;
            }
            set
            {
                this.WarningsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuzzyEditDistanceTaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class FuzzyEditDistanceTaskResult : MQS.TasksService.TaskResult
    {
        
        private MQS.TasksService.FuzzyEditDistanceReport ReportField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceReport Report
        {
            get
            {
                return this.ReportField;
            }
            set
            {
                this.ReportField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LevenshteinEditDistanceTaskResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class LevenshteinEditDistanceTaskResult : MQS.TasksService.TaskResult
    {
        
        private MQS.TasksService.LevenshteinEditDistanceReport ReportField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceReport Report
        {
            get
            {
                return this.ReportField;
            }
            set
            {
                this.ReportField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatisticsResultForLang", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class StatisticsResultForLang : object
    {
        
        private byte[] ResultDataField;
        
        private string TargetLangCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetLangCode
        {
            get
            {
                return this.TargetLangCodeField;
            }
            set
            {
                this.TargetLangCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTranslationResultForLang", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class PostTranslationResultForLang : object
    {
        
        private MQS.TasksService.PostTransAnalysisReportForDocument[] ByDocumentField;
        
        private MQS.TasksService.PostTransAnalysisReportForUser[] ByUserField;
        
        private MQS.TasksService.PostTransAnalysisReportItem SummaryField;
        
        private string TargetLangCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTransAnalysisReportForDocument[] ByDocument
        {
            get
            {
                return this.ByDocumentField;
            }
            set
            {
                this.ByDocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTransAnalysisReportForUser[] ByUser
        {
            get
            {
                return this.ByUserField;
            }
            set
            {
                this.ByUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTransAnalysisReportItem Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetLangCode
        {
            get
            {
                return this.TargetLangCodeField;
            }
            set
            {
                this.TargetLangCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTransAnalysisReportItem", Namespace="http://kilgray.com/memoqservices/2007")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TasksService.PostTransAnalysisReportForUser))]
    public partial class PostTransAnalysisReportItem : object
    {
        
        private MQS.TasksService.PostTranslationReportCounts AllField;
        
        private MQS.TasksService.PostTranslationReportCounts AutoPropagatedField;
        
        private MQS.TasksService.PostTranslationReportCounts FragmentsField;
        
        private MQS.TasksService.PostTranslationReportCounts Hit100Field;
        
        private MQS.TasksService.PostTranslationReportCounts Hit101Field;
        
        private MQS.TasksService.PostTranslationReportCounts Hit50_74Field;
        
        private MQS.TasksService.PostTranslationReportCounts Hit75_84Field;
        
        private MQS.TasksService.PostTranslationReportCounts Hit85_94Field;
        
        private MQS.TasksService.PostTranslationReportCounts Hit95_99Field;
        
        private MQS.TasksService.PostTranslationReportCounts NoMatchField;
        
        private MQS.TasksService.PostTranslationReportCounts XTranslatedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTranslationReportCounts All
        {
            get
            {
                return this.AllField;
            }
            set
            {
                this.AllField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTranslationReportCounts AutoPropagated
        {
            get
            {
                return this.AutoPropagatedField;
            }
            set
            {
                this.AutoPropagatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTranslationReportCounts Fragments
        {
            get
            {
                return this.FragmentsField;
            }
            set
            {
                this.FragmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTranslationReportCounts Hit100
        {
            get
            {
                return this.Hit100Field;
            }
            set
            {
                this.Hit100Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTranslationReportCounts Hit101
        {
            get
            {
                return this.Hit101Field;
            }
            set
            {
                this.Hit101Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTranslationReportCounts Hit50_74
        {
            get
            {
                return this.Hit50_74Field;
            }
            set
            {
                this.Hit50_74Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTranslationReportCounts Hit75_84
        {
            get
            {
                return this.Hit75_84Field;
            }
            set
            {
                this.Hit75_84Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTranslationReportCounts Hit85_94
        {
            get
            {
                return this.Hit85_94Field;
            }
            set
            {
                this.Hit85_94Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTranslationReportCounts Hit95_99
        {
            get
            {
                return this.Hit95_99Field;
            }
            set
            {
                this.Hit95_99Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTranslationReportCounts NoMatch
        {
            get
            {
                return this.NoMatchField;
            }
            set
            {
                this.NoMatchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTranslationReportCounts XTranslated
        {
            get
            {
                return this.XTranslatedField;
            }
            set
            {
                this.XTranslatedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTransAnalysisReportForDocument", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class PostTransAnalysisReportForDocument : object
    {
        
        private MQS.TasksService.PostTransAnalysisReportForUser[] ByUserField;
        
        private System.Guid DocumentGuidField;
        
        private MQS.TasksService.PostTransAnalysisReportItem SummaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTransAnalysisReportForUser[] ByUser
        {
            get
            {
                return this.ByUserField;
            }
            set
            {
                this.ByUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentGuid
        {
            get
            {
                return this.DocumentGuidField;
            }
            set
            {
                this.DocumentGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.PostTransAnalysisReportItem Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTransAnalysisReportForUser", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class PostTransAnalysisReportForUser : MQS.TasksService.PostTransAnalysisReportItem
    {
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTranslationReportCounts", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class PostTranslationReportCounts : object
    {
        
        private int SegmentCountField;
        
        private int SourceAsianCharCountField;
        
        private int SourceCharCountField;
        
        private int SourceNonAsianWordCountField;
        
        private int SourceTagCountField;
        
        private int SourceWordCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SegmentCount
        {
            get
            {
                return this.SegmentCountField;
            }
            set
            {
                this.SegmentCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourceAsianCharCount
        {
            get
            {
                return this.SourceAsianCharCountField;
            }
            set
            {
                this.SourceAsianCharCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourceCharCount
        {
            get
            {
                return this.SourceCharCountField;
            }
            set
            {
                this.SourceCharCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourceNonAsianWordCount
        {
            get
            {
                return this.SourceNonAsianWordCountField;
            }
            set
            {
                this.SourceNonAsianWordCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourceTagCount
        {
            get
            {
                return this.SourceTagCountField;
            }
            set
            {
                this.SourceTagCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourceWordCount
        {
            get
            {
                return this.SourceWordCountField;
            }
            set
            {
                this.SourceWordCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmAndUpdateDocError", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class ConfirmAndUpdateDocError : object
    {
        
        private System.Guid DocumentGuidField;
        
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentGuid
        {
            get
            {
                return this.DocumentGuidField;
            }
            set
            {
                this.DocumentGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XTranslateDocumentResult", Namespace="http://schemas.datacontract.org/2004/07/MemoQServices")]
    public partial class XTranslateDocumentResult : object
    {
        
        private System.Guid DocumentGuidField;
        
        private int NumberOfCandidatesField;
        
        private int NumberOfRowsField;
        
        private int NumberOfXTranslatedRowsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentGuid
        {
            get
            {
                return this.DocumentGuidField;
            }
            set
            {
                this.DocumentGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfCandidates
        {
            get
            {
                return this.NumberOfCandidatesField;
            }
            set
            {
                this.NumberOfCandidatesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfRows
        {
            get
            {
                return this.NumberOfRowsField;
            }
            set
            {
                this.NumberOfRowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfXTranslatedRows
        {
            get
            {
                return this.NumberOfXTranslatedRowsField;
            }
            set
            {
                this.NumberOfXTranslatedRowsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QAReport", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class QAReport : object
    {
        
        private string DetailedReportField;
        
        private MQS.TasksService.QAReportForDocument[] ReportsPerDocumentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailedReport
        {
            get
            {
                return this.DetailedReportField;
            }
            set
            {
                this.DetailedReportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.QAReportForDocument[] ReportsPerDocument
        {
            get
            {
                return this.ReportsPerDocumentField;
            }
            set
            {
                this.ReportsPerDocumentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QAReportForDocument", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class QAReportForDocument : object
    {
        
        private System.Guid DocumentGuidField;
        
        private string DocumentNameField;
        
        private int NumberOfErrorsField;
        
        private int NumberOfUnignoredWarningsField;
        
        private int NumberOfWarningsField;
        
        private string TargetLanguageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentGuid
        {
            get
            {
                return this.DocumentGuidField;
            }
            set
            {
                this.DocumentGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName
        {
            get
            {
                return this.DocumentNameField;
            }
            set
            {
                this.DocumentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfErrors
        {
            get
            {
                return this.NumberOfErrorsField;
            }
            set
            {
                this.NumberOfErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfUnignoredWarnings
        {
            get
            {
                return this.NumberOfUnignoredWarningsField;
            }
            set
            {
                this.NumberOfUnignoredWarningsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfWarnings
        {
            get
            {
                return this.NumberOfWarningsField;
            }
            set
            {
                this.NumberOfWarningsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetLanguage
        {
            get
            {
                return this.TargetLanguageField;
            }
            set
            {
                this.TargetLanguageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreTranslateProblem", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class PreTranslateProblem : object
    {
        
        private System.Nullable<System.Guid> DocumentGuidField;
        
        private string ProblemDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> DocumentGuid
        {
            get
            {
                return this.DocumentGuidField;
            }
            set
            {
                this.DocumentGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProblemDescription
        {
            get
            {
                return this.ProblemDescriptionField;
            }
            set
            {
                this.ProblemDescriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBXImportResults", Namespace="http://schemas.datacontract.org/2004/07/MemoQServices")]
    public enum TBXImportResults : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessWithWarning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingTBX = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingXCS = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidZIP = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidXCSReference = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TBXDTDError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XCSDTDError = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TBAlreadyExists = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherError = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuzzyEditDistanceReport", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class FuzzyEditDistanceReport : object
    {
        
        private MQS.TasksService.FuzzyEditDistanceResultForLang[] ByLanguageField;
        
        private System.Nullable<System.Guid> ReportIdField;
        
        private MQS.TasksService.FuzzyEditDistanceResult TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResultForLang[] ByLanguage
        {
            get
            {
                return this.ByLanguageField;
            }
            set
            {
                this.ByLanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ReportId
        {
            get
            {
                return this.ReportIdField;
            }
            set
            {
                this.ReportIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResult Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuzzyEditDistanceResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class FuzzyEditDistanceResult : object
    {
        
        private int NoMatchField;
        
        private int Rate100Field;
        
        private int Rate50_74Field;
        
        private int Rate75_84Field;
        
        private int Rate85_94Field;
        
        private int Rate95_99Field;
        
        private int SegmentsField;
        
        private int WordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoMatch
        {
            get
            {
                return this.NoMatchField;
            }
            set
            {
                this.NoMatchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rate100
        {
            get
            {
                return this.Rate100Field;
            }
            set
            {
                this.Rate100Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rate50_74
        {
            get
            {
                return this.Rate50_74Field;
            }
            set
            {
                this.Rate50_74Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rate75_84
        {
            get
            {
                return this.Rate75_84Field;
            }
            set
            {
                this.Rate75_84Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rate85_94
        {
            get
            {
                return this.Rate85_94Field;
            }
            set
            {
                this.Rate85_94Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rate95_99
        {
            get
            {
                return this.Rate95_99Field;
            }
            set
            {
                this.Rate95_99Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Segments
        {
            get
            {
                return this.SegmentsField;
            }
            set
            {
                this.SegmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Words
        {
            get
            {
                return this.WordsField;
            }
            set
            {
                this.WordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuzzyEditDistanceResultForLang", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class FuzzyEditDistanceResultForLang : object
    {
        
        private MQS.TasksService.FuzzyEditDistanceResultForDocument[] ByDocumentField;
        
        private string TargetLangCodeField;
        
        private MQS.TasksService.FuzzyEditDistanceResult TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResultForDocument[] ByDocument
        {
            get
            {
                return this.ByDocumentField;
            }
            set
            {
                this.ByDocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetLangCode
        {
            get
            {
                return this.TargetLangCodeField;
            }
            set
            {
                this.TargetLangCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResult Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuzzyEditDistanceResultForDocument", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class FuzzyEditDistanceResultForDocument : object
    {
        
        private double AverageFuzzyDistanceField;
        
        private double AverageMatchRateField;
        
        private System.Guid DocumentGuidField;
        
        private string DocumentNameField;
        
        private MQS.TasksService.FuzzyEditDistanceResult MachineTranslatedStatsField;
        
        private MQS.TasksService.FuzzyEditDistanceResult NoMatchInsertedStatsField;
        
        private MQS.TasksService.FuzzyEditDistanceResult Rate100StatsField;
        
        private MQS.TasksService.FuzzyEditDistanceResult Rate101StatsField;
        
        private MQS.TasksService.FuzzyEditDistanceResult Rate50_74StatsField;
        
        private MQS.TasksService.FuzzyEditDistanceResult Rate75_84StatsField;
        
        private MQS.TasksService.FuzzyEditDistanceResult Rate85_94StatsField;
        
        private MQS.TasksService.FuzzyEditDistanceResult Rate95_99StatsField;
        
        private MQS.TasksService.FuzzyEditDistanceResult TotalField;
        
        private MQS.TasksService.FuzzyEditDistanceResult XTranslatedStatsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AverageFuzzyDistance
        {
            get
            {
                return this.AverageFuzzyDistanceField;
            }
            set
            {
                this.AverageFuzzyDistanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AverageMatchRate
        {
            get
            {
                return this.AverageMatchRateField;
            }
            set
            {
                this.AverageMatchRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentGuid
        {
            get
            {
                return this.DocumentGuidField;
            }
            set
            {
                this.DocumentGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName
        {
            get
            {
                return this.DocumentNameField;
            }
            set
            {
                this.DocumentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResult MachineTranslatedStats
        {
            get
            {
                return this.MachineTranslatedStatsField;
            }
            set
            {
                this.MachineTranslatedStatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResult NoMatchInsertedStats
        {
            get
            {
                return this.NoMatchInsertedStatsField;
            }
            set
            {
                this.NoMatchInsertedStatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResult Rate100Stats
        {
            get
            {
                return this.Rate100StatsField;
            }
            set
            {
                this.Rate100StatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResult Rate101Stats
        {
            get
            {
                return this.Rate101StatsField;
            }
            set
            {
                this.Rate101StatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResult Rate50_74Stats
        {
            get
            {
                return this.Rate50_74StatsField;
            }
            set
            {
                this.Rate50_74StatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResult Rate75_84Stats
        {
            get
            {
                return this.Rate75_84StatsField;
            }
            set
            {
                this.Rate75_84StatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResult Rate85_94Stats
        {
            get
            {
                return this.Rate85_94StatsField;
            }
            set
            {
                this.Rate85_94StatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResult Rate95_99Stats
        {
            get
            {
                return this.Rate95_99StatsField;
            }
            set
            {
                this.Rate95_99StatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResult Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.FuzzyEditDistanceResult XTranslatedStats
        {
            get
            {
                return this.XTranslatedStatsField;
            }
            set
            {
                this.XTranslatedStatsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LevenshteinEditDistanceReport", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class LevenshteinEditDistanceReport : object
    {
        
        private MQS.TasksService.LevenshteinEditDistanceResultForLang[] ByLanguageField;
        
        private System.Nullable<System.Guid> ReportIdField;
        
        private MQS.TasksService.LevenshteinEditDistanceResult TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResultForLang[] ByLanguage
        {
            get
            {
                return this.ByLanguageField;
            }
            set
            {
                this.ByLanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ReportId
        {
            get
            {
                return this.ReportIdField;
            }
            set
            {
                this.ReportIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResult Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LevenshteinEditDistanceResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class LevenshteinEditDistanceResult : object
    {
        
        private int AbsoluteEditDistanceField;
        
        private int EditedSegmentsField;
        
        private double NormalizedEditDistanceField;
        
        private int SegmentsField;
        
        private int WordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AbsoluteEditDistance
        {
            get
            {
                return this.AbsoluteEditDistanceField;
            }
            set
            {
                this.AbsoluteEditDistanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EditedSegments
        {
            get
            {
                return this.EditedSegmentsField;
            }
            set
            {
                this.EditedSegmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NormalizedEditDistance
        {
            get
            {
                return this.NormalizedEditDistanceField;
            }
            set
            {
                this.NormalizedEditDistanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Segments
        {
            get
            {
                return this.SegmentsField;
            }
            set
            {
                this.SegmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Words
        {
            get
            {
                return this.WordsField;
            }
            set
            {
                this.WordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LevenshteinEditDistanceResultForLang", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class LevenshteinEditDistanceResultForLang : object
    {
        
        private MQS.TasksService.LevenshteinEditDistanceResultForDocument[] ByDocumentField;
        
        private string TargetLangCodeField;
        
        private MQS.TasksService.LevenshteinEditDistanceResult TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResultForDocument[] ByDocument
        {
            get
            {
                return this.ByDocumentField;
            }
            set
            {
                this.ByDocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetLangCode
        {
            get
            {
                return this.TargetLangCodeField;
            }
            set
            {
                this.TargetLangCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResult Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LevenshteinEditDistanceResultForDocument", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class LevenshteinEditDistanceResultForDocument : object
    {
        
        private double AverageMatchRateField;
        
        private System.Guid DocumentGuidField;
        
        private string DocumentNameField;
        
        private MQS.TasksService.LevenshteinEditDistanceResult MachineTranslatedStatsField;
        
        private MQS.TasksService.LevenshteinEditDistanceResult NoMatchInsertedStatsField;
        
        private double NormalizedEditDistanceField;
        
        private MQS.TasksService.LevenshteinEditDistanceResult Rate100StatsField;
        
        private MQS.TasksService.LevenshteinEditDistanceResult Rate101StatsField;
        
        private MQS.TasksService.LevenshteinEditDistanceResult Rate50_74StatsField;
        
        private MQS.TasksService.LevenshteinEditDistanceResult Rate75_84StatsField;
        
        private MQS.TasksService.LevenshteinEditDistanceResult Rate85_94StatsField;
        
        private MQS.TasksService.LevenshteinEditDistanceResult Rate95_99StatsField;
        
        private MQS.TasksService.LevenshteinEditDistanceResult TotalField;
        
        private MQS.TasksService.LevenshteinEditDistanceResult XTranslatedStatsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AverageMatchRate
        {
            get
            {
                return this.AverageMatchRateField;
            }
            set
            {
                this.AverageMatchRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentGuid
        {
            get
            {
                return this.DocumentGuidField;
            }
            set
            {
                this.DocumentGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName
        {
            get
            {
                return this.DocumentNameField;
            }
            set
            {
                this.DocumentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResult MachineTranslatedStats
        {
            get
            {
                return this.MachineTranslatedStatsField;
            }
            set
            {
                this.MachineTranslatedStatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResult NoMatchInsertedStats
        {
            get
            {
                return this.NoMatchInsertedStatsField;
            }
            set
            {
                this.NoMatchInsertedStatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NormalizedEditDistance
        {
            get
            {
                return this.NormalizedEditDistanceField;
            }
            set
            {
                this.NormalizedEditDistanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResult Rate100Stats
        {
            get
            {
                return this.Rate100StatsField;
            }
            set
            {
                this.Rate100StatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResult Rate101Stats
        {
            get
            {
                return this.Rate101StatsField;
            }
            set
            {
                this.Rate101StatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResult Rate50_74Stats
        {
            get
            {
                return this.Rate50_74StatsField;
            }
            set
            {
                this.Rate50_74StatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResult Rate75_84Stats
        {
            get
            {
                return this.Rate75_84StatsField;
            }
            set
            {
                this.Rate75_84StatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResult Rate85_94Stats
        {
            get
            {
                return this.Rate85_94StatsField;
            }
            set
            {
                this.Rate85_94StatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResult Rate95_99Stats
        {
            get
            {
                return this.Rate95_99StatsField;
            }
            set
            {
                this.Rate95_99StatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResult Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TasksService.LevenshteinEditDistanceResult XTranslatedStats
        {
            get
            {
                return this.XTranslatedStatsField;
            }
            set
            {
                this.XTranslatedStatsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskNotFinishedFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TaskNotFinishedFault : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskDoesNotExistFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TaskDoesNotExistFault : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TMFault : object
    {
        
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoLicenseFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class NoLicenseFault : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnauthorizedAccessFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class UnauthorizedAccessFault : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpectedFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class ExpectedFault : object
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kilgray.com/memoqservices/2007", ConfigurationName="MQS.TasksService.ITasksService")]
    public interface ITasksService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskStatus", ReplyAction="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskStatusUnexpectedFaultF" +
            "ault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskStatusGenericFaultFaul" +
            "t", Name="GenericFault")]
        MQS.TasksService.TaskInfo GetTaskStatus(System.Guid taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskStatus", ReplyAction="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskStatusResponse")]
        System.Threading.Tasks.Task<MQS.TasksService.TaskInfo> GetTaskStatusAsync(System.Guid taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTasksStatus", ReplyAction="http://kilgray.com/memoqservices/2007/ITasksService/GetTasksStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTasksStatusUnexpectedFault" +
            "Fault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTasksStatusGenericFaultFau" +
            "lt", Name="GenericFault")]
        MQS.TasksService.TaskInfo[] GetTasksStatus(System.Guid[] taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTasksStatus", ReplyAction="http://kilgray.com/memoqservices/2007/ITasksService/GetTasksStatusResponse")]
        System.Threading.Tasks.Task<MQS.TasksService.TaskInfo[]> GetTasksStatusAsync(System.Guid[] taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITasksService/CancelTask", ReplyAction="http://kilgray.com/memoqservices/2007/ITasksService/CancelTaskResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/CancelTaskUnexpectedFaultFaul" +
            "t", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/CancelTaskGenericFaultFault", Name="GenericFault")]
        MQS.TasksService.TaskInfo CancelTask(System.Guid taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITasksService/CancelTask", ReplyAction="http://kilgray.com/memoqservices/2007/ITasksService/CancelTaskResponse")]
        System.Threading.Tasks.Task<MQS.TasksService.TaskInfo> CancelTaskAsync(System.Guid taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskResult", ReplyAction="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskResultResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskResultUnexpectedFaultF" +
            "ault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskResultGenericFaultFaul" +
            "t", Name="GenericFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.TaskNotFinishedFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskResultTaskNotFinishedF" +
            "aultFault", Name="TaskNotFinishedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.TaskDoesNotExistFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskResultTaskDoesNotExist" +
            "FaultFault", Name="TaskDoesNotExistFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.TMFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskResultTMFaultFault", Name="TMFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.NoLicenseFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskResultNoLicenseFaultFa" +
            "ult", Name="NoLicenseFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.UnauthorizedAccessFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskResultUnauthorizedAcce" +
            "ssFaultFault", Name="UnauthorizedAccessFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TasksService.ExpectedFault), Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskResultExpectedFaultFau" +
            "lt", Name="ExpectedFault")]
        MQS.TasksService.TaskResult GetTaskResult(System.Guid taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskResult", ReplyAction="http://kilgray.com/memoqservices/2007/ITasksService/GetTaskResultResponse")]
        System.Threading.Tasks.Task<MQS.TasksService.TaskResult> GetTaskResultAsync(System.Guid taskId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ITasksServiceChannel : MQS.TasksService.ITasksService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class TasksServiceClient : System.ServiceModel.ClientBase<MQS.TasksService.ITasksService>, MQS.TasksService.ITasksService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TasksServiceClient() : 
                base(TasksServiceClient.GetDefaultBinding(), TasksServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.serviceEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TasksServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TasksServiceClient.GetBindingForEndpoint(endpointConfiguration), TasksServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TasksServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TasksServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TasksServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TasksServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TasksServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public MQS.TasksService.TaskInfo GetTaskStatus(System.Guid taskId)
        {
            return base.Channel.GetTaskStatus(taskId);
        }
        
        public System.Threading.Tasks.Task<MQS.TasksService.TaskInfo> GetTaskStatusAsync(System.Guid taskId)
        {
            return base.Channel.GetTaskStatusAsync(taskId);
        }
        
        public MQS.TasksService.TaskInfo[] GetTasksStatus(System.Guid[] taskId)
        {
            return base.Channel.GetTasksStatus(taskId);
        }
        
        public System.Threading.Tasks.Task<MQS.TasksService.TaskInfo[]> GetTasksStatusAsync(System.Guid[] taskId)
        {
            return base.Channel.GetTasksStatusAsync(taskId);
        }
        
        public MQS.TasksService.TaskInfo CancelTask(System.Guid taskId)
        {
            return base.Channel.CancelTask(taskId);
        }
        
        public System.Threading.Tasks.Task<MQS.TasksService.TaskInfo> CancelTaskAsync(System.Guid taskId)
        {
            return base.Channel.CancelTaskAsync(taskId);
        }
        
        public MQS.TasksService.TaskResult GetTaskResult(System.Guid taskId)
        {
            return base.Channel.GetTaskResult(taskId);
        }
        
        public System.Threading.Tasks.Task<MQS.TasksService.TaskResult> GetTaskResultAsync(System.Guid taskId)
        {
            return base.Channel.GetTaskResultAsync(taskId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.serviceEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.serviceEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("https://65.21.34.61:3280/memoqservices/tasks/TasksService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TasksServiceClient.GetBindingForEndpoint(EndpointConfiguration.serviceEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TasksServiceClient.GetEndpointAddress(EndpointConfiguration.serviceEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            serviceEndPoint,
        }
    }
}
