//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MQS.TM
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TM.HeavyResourceInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TM.TMInfo))]
    public partial class ResourceInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private System.Guid GuidField;
        
        private string NameField;
        
        private bool ReadonlyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Readonly
        {
            get
            {
                return this.ReadonlyField;
            }
            set
            {
                this.ReadonlyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeavyResourceInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TM.TMInfo))]
    public partial class HeavyResourceInfo : MQS.TM.ResourceInfo
    {
        
        private string ClientField;
        
        private string DomainField;
        
        private bool IsUsedInProjectField;
        
        private System.DateTime LastModifiedField;
        
        private System.DateTime LastUsedField;
        
        private string ProjectField;
        
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain
        {
            get
            {
                return this.DomainField;
            }
            set
            {
                this.DomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUsedInProject
        {
            get
            {
                return this.IsUsedInProjectField;
            }
            set
            {
                this.IsUsedInProjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModified
        {
            get
            {
                return this.LastModifiedField;
            }
            set
            {
                this.LastModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUsed
        {
            get
            {
                return this.LastUsedField;
            }
            set
            {
                this.LastUsedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Project
        {
            get
            {
                return this.ProjectField;
            }
            set
            {
                this.ProjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TMInfo : MQS.TM.HeavyResourceInfo
    {
        
        private bool AllowMultipleField;
        
        private bool AllowReverseLookupField;
        
        private string CreatorUsernameField;
        
        private int NumOfEntriesField;
        
        private MQS.TM.TMOptimizationPreference OptimizationPreferenceField;
        
        private string SourceLanguageCodeField;
        
        private bool StoreDocumentFullPathField;
        
        private bool StoreDocumentNameField;
        
        private bool StoreFormattingField;
        
        private MQS.TM.TMEngineType TMEngineTypeField;
        
        private string TargetLanguageCodeField;
        
        private bool UseContextField;
        
        private bool UseIceSpiceContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowMultiple
        {
            get
            {
                return this.AllowMultipleField;
            }
            set
            {
                this.AllowMultipleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowReverseLookup
        {
            get
            {
                return this.AllowReverseLookupField;
            }
            set
            {
                this.AllowReverseLookupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatorUsername
        {
            get
            {
                return this.CreatorUsernameField;
            }
            set
            {
                this.CreatorUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfEntries
        {
            get
            {
                return this.NumOfEntriesField;
            }
            set
            {
                this.NumOfEntriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TM.TMOptimizationPreference OptimizationPreference
        {
            get
            {
                return this.OptimizationPreferenceField;
            }
            set
            {
                this.OptimizationPreferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceLanguageCode
        {
            get
            {
                return this.SourceLanguageCodeField;
            }
            set
            {
                this.SourceLanguageCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StoreDocumentFullPath
        {
            get
            {
                return this.StoreDocumentFullPathField;
            }
            set
            {
                this.StoreDocumentFullPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StoreDocumentName
        {
            get
            {
                return this.StoreDocumentNameField;
            }
            set
            {
                this.StoreDocumentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StoreFormatting
        {
            get
            {
                return this.StoreFormattingField;
            }
            set
            {
                this.StoreFormattingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TM.TMEngineType TMEngineType
        {
            get
            {
                return this.TMEngineTypeField;
            }
            set
            {
                this.TMEngineTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetLanguageCode
        {
            get
            {
                return this.TargetLanguageCodeField;
            }
            set
            {
                this.TargetLanguageCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseContext
        {
            get
            {
                return this.UseContextField;
            }
            set
            {
                this.UseContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseIceSpiceContext
        {
            get
            {
                return this.UseIceSpiceContextField;
            }
            set
            {
                this.UseIceSpiceContextField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMOptimizationPreference", Namespace="http://schemas.datacontract.org/2004/07/MemoQServices")]
    public enum TMOptimizationPreference : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Recall = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mixed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fast = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMEngineType", Namespace="http://kilgray.com/memoqservices/2007")]
    public enum TMEngineType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OldTMEngine = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NGTMEngine = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceListFilter", Namespace="http://kilgray.com/memoqservices/2007")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TM.TMListFilter))]
    public partial class ResourceListFilter : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClientField;
        
        private string DomainField;
        
        private System.Nullable<System.DateTime> LastModifiedAfterField;
        
        private System.Nullable<System.DateTime> LastModifiedBeforeField;
        
        private System.Nullable<System.DateTime> LastUsedAfterField;
        
        private System.Nullable<System.DateTime> LastUsedBeforeField;
        
        private string NameOrDescriptionField;
        
        private System.Nullable<int> NumberOfEntriesMaxField;
        
        private System.Nullable<int> NumberOfEntriesMinField;
        
        private string ProjectField;
        
        private string SubjectField;
        
        private System.Nullable<bool> UsedInProjectField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain
        {
            get
            {
                return this.DomainField;
            }
            set
            {
                this.DomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastModifiedAfter
        {
            get
            {
                return this.LastModifiedAfterField;
            }
            set
            {
                this.LastModifiedAfterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastModifiedBefore
        {
            get
            {
                return this.LastModifiedBeforeField;
            }
            set
            {
                this.LastModifiedBeforeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUsedAfter
        {
            get
            {
                return this.LastUsedAfterField;
            }
            set
            {
                this.LastUsedAfterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUsedBefore
        {
            get
            {
                return this.LastUsedBeforeField;
            }
            set
            {
                this.LastUsedBeforeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameOrDescription
        {
            get
            {
                return this.NameOrDescriptionField;
            }
            set
            {
                this.NameOrDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfEntriesMax
        {
            get
            {
                return this.NumberOfEntriesMaxField;
            }
            set
            {
                this.NumberOfEntriesMaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfEntriesMin
        {
            get
            {
                return this.NumberOfEntriesMinField;
            }
            set
            {
                this.NumberOfEntriesMinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Project
        {
            get
            {
                return this.ProjectField;
            }
            set
            {
                this.ProjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> UsedInProject
        {
            get
            {
                return this.UsedInProjectField;
            }
            set
            {
                this.UsedInProjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMListFilter", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TMListFilter : MQS.TM.ResourceListFilter
    {
        
        private bool LazyLanguageCheckField;
        
        private string SourceLangCodeField;
        
        private string TargetLangCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LazyLanguageCheck
        {
            get
            {
                return this.LazyLanguageCheckField;
            }
            set
            {
                this.LazyLanguageCheckField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceLangCode
        {
            get
            {
                return this.SourceLangCodeField;
            }
            set
            {
                this.SourceLangCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetLangCode
        {
            get
            {
                return this.TargetLangCodeField;
            }
            set
            {
                this.TargetLangCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceUpdateInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TM.HeavyResourceUpdateInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TM.TMUpdateInfo))]
    public partial class ResourceUpdateInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private System.Guid GuidField;
        
        private string NameField;
        
        private bool ReadonlyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Readonly
        {
            get
            {
                return this.ReadonlyField;
            }
            set
            {
                this.ReadonlyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeavyResourceUpdateInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TM.TMUpdateInfo))]
    public partial class HeavyResourceUpdateInfo : MQS.TM.ResourceUpdateInfo
    {
        
        private string ClientField;
        
        private string DomainField;
        
        private string ProjectField;
        
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain
        {
            get
            {
                return this.DomainField;
            }
            set
            {
                this.DomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Project
        {
            get
            {
                return this.ProjectField;
            }
            set
            {
                this.ProjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMUpdateInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TMUpdateInfo : MQS.TM.HeavyResourceUpdateInfo
    {
        
        private System.Nullable<MQS.TM.TMOptimizationPreference> OptimizationPreferenceField;
        
        private System.Nullable<bool> StoreDocumentFullPathField;
        
        private System.Nullable<bool> StoreDocumentNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<MQS.TM.TMOptimizationPreference> OptimizationPreference
        {
            get
            {
                return this.OptimizationPreferenceField;
            }
            set
            {
                this.OptimizationPreferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> StoreDocumentFullPath
        {
            get
            {
                return this.StoreDocumentFullPathField;
            }
            set
            {
                this.StoreDocumentFullPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> StoreDocumentName
        {
            get
            {
                return this.StoreDocumentNameField;
            }
            set
            {
                this.StoreDocumentNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TmxImportSettings", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TmxImportSettings : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CustomTagsAsMemoQTagsField;
        
        private bool ImportMemoQFormattingField;
        
        private bool ImportUtAsMemoQTagField;
        
        private bool ProcessTradosTmxField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CustomTagsAsMemoQTags
        {
            get
            {
                return this.CustomTagsAsMemoQTagsField;
            }
            set
            {
                this.CustomTagsAsMemoQTagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ImportMemoQFormatting
        {
            get
            {
                return this.ImportMemoQFormattingField;
            }
            set
            {
                this.ImportMemoQFormattingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ImportUtAsMemoQTag
        {
            get
            {
                return this.ImportUtAsMemoQTagField;
            }
            set
            {
                this.ImportUtAsMemoQTagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ProcessTradosTmx
        {
            get
            {
                return this.ProcessTradosTmxField;
            }
            set
            {
                this.ProcessTradosTmxField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TmxImportResult", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TmxImportResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AllSegmentCountField;
        
        private int ImportedSegmentCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllSegmentCount
        {
            get
            {
                return this.AllSegmentCountField;
            }
            set
            {
                this.AllSegmentCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImportedSegmentCount
        {
            get
            {
                return this.ImportedSegmentCountField;
            }
            set
            {
                this.ImportedSegmentCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupSegmentRequest", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class LookupSegmentRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool AdjustFuzzyMatchesField;
        
        private MQS.TM.InlineTagStrictness InlineTagStrictnessField;
        
        private int MatchThresholdField;
        
        private bool OnlyBestField;
        
        private bool OnlyUnambiguousField;
        
        private bool ReverseLookupField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AdjustFuzzyMatches
        {
            get
            {
                return this.AdjustFuzzyMatchesField;
            }
            set
            {
                this.AdjustFuzzyMatchesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TM.InlineTagStrictness InlineTagStrictness
        {
            get
            {
                return this.InlineTagStrictnessField;
            }
            set
            {
                this.InlineTagStrictnessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchThreshold
        {
            get
            {
                return this.MatchThresholdField;
            }
            set
            {
                this.MatchThresholdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OnlyBest
        {
            get
            {
                return this.OnlyBestField;
            }
            set
            {
                this.OnlyBestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OnlyUnambiguous
        {
            get
            {
                return this.OnlyUnambiguousField;
            }
            set
            {
                this.OnlyUnambiguousField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReverseLookup
        {
            get
            {
                return this.ReverseLookupField;
            }
            set
            {
                this.ReverseLookupField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InlineTagStrictness", Namespace="http://kilgray.com/memoqservices/2007")]
    public enum InlineTagStrictness : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Strict = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Medium = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Permissive = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConcordanceRequest", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class ConcordanceRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CaseSensitiveField;
        
        private bool NumericEquivalenceField;
        
        private int ResultsLimitField;
        
        private bool ReverseLookupField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CaseSensitive
        {
            get
            {
                return this.CaseSensitiveField;
            }
            set
            {
                this.CaseSensitiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NumericEquivalence
        {
            get
            {
                return this.NumericEquivalenceField;
            }
            set
            {
                this.NumericEquivalenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultsLimit
        {
            get
            {
                return this.ResultsLimitField;
            }
            set
            {
                this.ResultsLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReverseLookup
        {
            get
            {
                return this.ReverseLookupField;
            }
            set
            {
                this.ReverseLookupField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQS.TM.ImportTMMetadataSchemeResultInfo))]
    public partial class ResultInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DetailedMessageField;
        
        private string MainMessageField;
        
        private MQS.TM.ResultStatus ResultStatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailedMessage
        {
            get
            {
                return this.DetailedMessageField;
            }
            set
            {
                this.DetailedMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainMessage
        {
            get
            {
                return this.MainMessageField;
            }
            set
            {
                this.MainMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MQS.TM.ResultStatus ResultStatus
        {
            get
            {
                return this.ResultStatusField;
            }
            set
            {
                this.ResultStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportTMMetadataSchemeResultInfo", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class ImportTMMetadataSchemeResultInfo : MQS.TM.ResultInfo
    {
        
        private string[] ConflictedFieldsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ConflictedFields
        {
            get
            {
                return this.ConflictedFieldsField;
            }
            set
            {
                this.ConflictedFieldsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultStatus", Namespace="http://schemas.datacontract.org/2004/07/MemoQServices")]
    public enum ResultStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnexpectedFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class UnexpectedFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string StackTraceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class GenericFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidSessionIdFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class InvalidSessionIdFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnauthorizedAccessFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class UnauthorizedAccessFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoLicenseFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class NoLicenseFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class TMFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestXmlFormatFault", Namespace="http://kilgray.com/memoqservices/2007")]
    public partial class RequestXmlFormatFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kilgray.com/memoqservices/2007", ConfigurationName="MQS.TM.ITMService")]
    public interface ITMService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/CreateAndPublish", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/CreateAndPublishResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/CreateAndPublishUnexpectedFaultF" +
            "ault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/CreateAndPublishGenericFaultFaul" +
            "t", Name="GenericFault")]
        System.Guid CreateAndPublish(MQS.TM.TMInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/CreateAndPublish", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/CreateAndPublishResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateAndPublishAsync(MQS.TM.TMInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/ListTMs", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/ListTMsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/ListTMsUnexpectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/ListTMsGenericFaultFault", Name="GenericFault")]
        MQS.TM.TMInfo[] ListTMs(string srcLang, string targetLang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/ListTMs", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/ListTMsResponse")]
        System.Threading.Tasks.Task<MQS.TM.TMInfo[]> ListTMsAsync(string srcLang, string targetLang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/ListTMs2", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/ListTMs2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/ListTMs2UnexpectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/ListTMs2GenericFaultFault", Name="GenericFault")]
        MQS.TM.TMInfo[] ListTMs2(MQS.TM.TMListFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/ListTMs2", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/ListTMs2Response")]
        System.Threading.Tasks.Task<MQS.TM.TMInfo[]> ListTMs2Async(MQS.TM.TMListFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/GetTMInfo", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/GetTMInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/GetTMInfoUnexpectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/GetTMInfoGenericFaultFault", Name="GenericFault")]
        MQS.TM.TMInfo GetTMInfo(System.Guid tmGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/GetTMInfo", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/GetTMInfoResponse")]
        System.Threading.Tasks.Task<MQS.TM.TMInfo> GetTMInfoAsync(System.Guid tmGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/UpdateProperties", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/UpdatePropertiesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/UpdatePropertiesUnexpectedFaultF" +
            "ault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/UpdatePropertiesGenericFaultFaul" +
            "t", Name="GenericFault")]
        void UpdateProperties(MQS.TM.TMUpdateInfo updateInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/UpdateProperties", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/UpdatePropertiesResponse")]
        System.Threading.Tasks.Task UpdatePropertiesAsync(MQS.TM.TMUpdateInfo updateInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/DeleteTM", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/DeleteTMResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/DeleteTMUnexpectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/DeleteTMGenericFaultFault", Name="GenericFault")]
        void DeleteTM(System.Guid tmGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/DeleteTM", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/DeleteTMResponse")]
        System.Threading.Tasks.Task DeleteTMAsync(System.Guid tmGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXImport", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXImportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXImportUnexpectedF" +
            "aultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXImportGenericFaul" +
            "tFault", Name="GenericFault")]
        System.Guid BeginChunkedTMXImport(System.Guid tmGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXImport", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXImportResponse")]
        System.Threading.Tasks.Task<System.Guid> BeginChunkedTMXImportAsync(System.Guid tmGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXImport2", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXImport2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXImport2Unexpected" +
            "FaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXImport2GenericFau" +
            "ltFault", Name="GenericFault")]
        System.Guid BeginChunkedTMXImport2(System.Guid tmGuid, MQS.TM.TmxImportSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXImport2", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXImport2Response")]
        System.Threading.Tasks.Task<System.Guid> BeginChunkedTMXImport2Async(System.Guid tmGuid, MQS.TM.TmxImportSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/AddNextTMXChunk", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/AddNextTMXChunkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/AddNextTMXChunkUnexpectedFaultFa" +
            "ult", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/AddNextTMXChunkGenericFaultFault" +
            "", Name="GenericFault")]
        void AddNextTMXChunk(System.Guid sessionId, byte[] tmxData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/AddNextTMXChunk", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/AddNextTMXChunkResponse")]
        System.Threading.Tasks.Task AddNextTMXChunkAsync(System.Guid sessionId, byte[] tmxData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/EndChunkedTMXImport", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/EndChunkedTMXImportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/EndChunkedTMXImportUnexpectedFau" +
            "ltFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/EndChunkedTMXImportGenericFaultF" +
            "ault", Name="GenericFault")]
        MQS.TM.TmxImportResult EndChunkedTMXImport(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/EndChunkedTMXImport", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/EndChunkedTMXImportResponse")]
        System.Threading.Tasks.Task<MQS.TM.TmxImportResult> EndChunkedTMXImportAsync(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXExport", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXExportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXExportUnexpectedF" +
            "aultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXExportGenericFaul" +
            "tFault", Name="GenericFault")]
        System.Guid BeginChunkedTMXExport(System.Guid tmGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXExport", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/BeginChunkedTMXExportResponse")]
        System.Threading.Tasks.Task<System.Guid> BeginChunkedTMXExportAsync(System.Guid tmGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/GetNextTMXChunk", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/GetNextTMXChunkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/GetNextTMXChunkUnexpectedFaultFa" +
            "ult", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/GetNextTMXChunkGenericFaultFault" +
            "", Name="GenericFault")]
        byte[] GetNextTMXChunk(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/GetNextTMXChunk", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/GetNextTMXChunkResponse")]
        System.Threading.Tasks.Task<byte[]> GetNextTMXChunkAsync(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/EndChunkedTMXExport", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/EndChunkedTMXExportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/EndChunkedTMXExportUnexpectedFau" +
            "ltFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/EndChunkedTMXExportGenericFaultF" +
            "ault", Name="GenericFault")]
        void EndChunkedTMXExport(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/EndChunkedTMXExport", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/EndChunkedTMXExportResponse")]
        System.Threading.Tasks.Task EndChunkedTMXExportAsync(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/LookupSegment", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/LookupSegmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.InvalidSessionIdFault), Action="http://kilgray.com/memoqservices/2007/ITMService/LookupSegmentInvalidSessionIdFau" +
            "ltFault", Name="InvalidSessionIdFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnauthorizedAccessFault), Action="http://kilgray.com/memoqservices/2007/ITMService/LookupSegmentUnauthorizedAccessF" +
            "aultFault", Name="UnauthorizedAccessFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.NoLicenseFault), Action="http://kilgray.com/memoqservices/2007/ITMService/LookupSegmentNoLicenseFaultFault" +
            "", Name="NoLicenseFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.TMFault), Action="http://kilgray.com/memoqservices/2007/ITMService/LookupSegmentTMFaultFault", Name="TMFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.RequestXmlFormatFault), Action="http://kilgray.com/memoqservices/2007/ITMService/LookupSegmentRequestXmlFormatFau" +
            "ltFault", Name="RequestXmlFormatFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/LookupSegmentUnexpectedFaultFaul" +
            "t", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/LookupSegmentGenericFaultFault", Name="GenericFault")]
        string LookupSegment(string sessionId, string lookupDataXml, System.Guid tmGuid, MQS.TM.LookupSegmentRequest options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/LookupSegment", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/LookupSegmentResponse")]
        System.Threading.Tasks.Task<string> LookupSegmentAsync(string sessionId, string lookupDataXml, System.Guid tmGuid, MQS.TM.LookupSegmentRequest options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/Concordance", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/ConcordanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.InvalidSessionIdFault), Action="http://kilgray.com/memoqservices/2007/ITMService/ConcordanceInvalidSessionIdFault" +
            "Fault", Name="InvalidSessionIdFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnauthorizedAccessFault), Action="http://kilgray.com/memoqservices/2007/ITMService/ConcordanceUnauthorizedAccessFau" +
            "ltFault", Name="UnauthorizedAccessFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.NoLicenseFault), Action="http://kilgray.com/memoqservices/2007/ITMService/ConcordanceNoLicenseFaultFault", Name="NoLicenseFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.TMFault), Action="http://kilgray.com/memoqservices/2007/ITMService/ConcordanceTMFaultFault", Name="TMFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/ConcordanceUnexpectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/ConcordanceGenericFaultFault", Name="GenericFault")]
        string Concordance(string sessionId, string searchExpression, System.Guid tmGuid, MQS.TM.ConcordanceRequest options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/Concordance", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/ConcordanceResponse")]
        System.Threading.Tasks.Task<string> ConcordanceAsync(string sessionId, string searchExpression, System.Guid tmGuid, MQS.TM.ConcordanceRequest options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/AddOrUpdateEntry", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/AddOrUpdateEntryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.InvalidSessionIdFault), Action="http://kilgray.com/memoqservices/2007/ITMService/AddOrUpdateEntryInvalidSessionId" +
            "FaultFault", Name="InvalidSessionIdFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnauthorizedAccessFault), Action="http://kilgray.com/memoqservices/2007/ITMService/AddOrUpdateEntryUnauthorizedAcce" +
            "ssFaultFault", Name="UnauthorizedAccessFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.NoLicenseFault), Action="http://kilgray.com/memoqservices/2007/ITMService/AddOrUpdateEntryNoLicenseFaultFa" +
            "ult", Name="NoLicenseFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.TMFault), Action="http://kilgray.com/memoqservices/2007/ITMService/AddOrUpdateEntryTMFaultFault", Name="TMFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.RequestXmlFormatFault), Action="http://kilgray.com/memoqservices/2007/ITMService/AddOrUpdateEntryRequestXmlFormat" +
            "FaultFault", Name="RequestXmlFormatFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/AddOrUpdateEntryUnexpectedFaultF" +
            "ault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/AddOrUpdateEntryGenericFaultFaul" +
            "t", Name="GenericFault")]
        void AddOrUpdateEntry(string sessionId, string segmentDataXml, System.Guid tmGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/AddOrUpdateEntry", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/AddOrUpdateEntryResponse")]
        System.Threading.Tasks.Task AddOrUpdateEntryAsync(string sessionId, string segmentDataXml, System.Guid tmGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/ImportTMMetadataSchemeFromXML", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/ImportTMMetadataSchemeFromXMLRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.UnexpectedFault), Action="http://kilgray.com/memoqservices/2007/ITMService/ImportTMMetadataSchemeFromXMLUne" +
            "xpectedFaultFault", Name="UnexpectedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MQS.TM.GenericFault), Action="http://kilgray.com/memoqservices/2007/ITMService/ImportTMMetadataSchemeFromXMLGen" +
            "ericFaultFault", Name="GenericFault")]
        MQS.TM.ImportTMMetadataSchemeResultInfo ImportTMMetadataSchemeFromXML(System.Guid tmGuid, string scheme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kilgray.com/memoqservices/2007/ITMService/ImportTMMetadataSchemeFromXML", ReplyAction="http://kilgray.com/memoqservices/2007/ITMService/ImportTMMetadataSchemeFromXMLRes" +
            "ponse")]
        System.Threading.Tasks.Task<MQS.TM.ImportTMMetadataSchemeResultInfo> ImportTMMetadataSchemeFromXMLAsync(System.Guid tmGuid, string scheme);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITMServiceChannel : MQS.TM.ITMService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TMServiceClient : System.ServiceModel.ClientBase<MQS.TM.ITMService>, MQS.TM.ITMService
    {
        
        public TMServiceClient()
        {
        }
        
        public TMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Guid CreateAndPublish(MQS.TM.TMInfo info)
        {
            return base.Channel.CreateAndPublish(info);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateAndPublishAsync(MQS.TM.TMInfo info)
        {
            return base.Channel.CreateAndPublishAsync(info);
        }
        
        public MQS.TM.TMInfo[] ListTMs(string srcLang, string targetLang)
        {
            return base.Channel.ListTMs(srcLang, targetLang);
        }
        
        public System.Threading.Tasks.Task<MQS.TM.TMInfo[]> ListTMsAsync(string srcLang, string targetLang)
        {
            return base.Channel.ListTMsAsync(srcLang, targetLang);
        }
        
        public MQS.TM.TMInfo[] ListTMs2(MQS.TM.TMListFilter filter)
        {
            return base.Channel.ListTMs2(filter);
        }
        
        public System.Threading.Tasks.Task<MQS.TM.TMInfo[]> ListTMs2Async(MQS.TM.TMListFilter filter)
        {
            return base.Channel.ListTMs2Async(filter);
        }
        
        public MQS.TM.TMInfo GetTMInfo(System.Guid tmGuid)
        {
            return base.Channel.GetTMInfo(tmGuid);
        }
        
        public System.Threading.Tasks.Task<MQS.TM.TMInfo> GetTMInfoAsync(System.Guid tmGuid)
        {
            return base.Channel.GetTMInfoAsync(tmGuid);
        }
        
        public void UpdateProperties(MQS.TM.TMUpdateInfo updateInfo)
        {
            base.Channel.UpdateProperties(updateInfo);
        }
        
        public System.Threading.Tasks.Task UpdatePropertiesAsync(MQS.TM.TMUpdateInfo updateInfo)
        {
            return base.Channel.UpdatePropertiesAsync(updateInfo);
        }
        
        public void DeleteTM(System.Guid tmGuid)
        {
            base.Channel.DeleteTM(tmGuid);
        }
        
        public System.Threading.Tasks.Task DeleteTMAsync(System.Guid tmGuid)
        {
            return base.Channel.DeleteTMAsync(tmGuid);
        }
        
        public System.Guid BeginChunkedTMXImport(System.Guid tmGuid)
        {
            return base.Channel.BeginChunkedTMXImport(tmGuid);
        }
        
        public System.Threading.Tasks.Task<System.Guid> BeginChunkedTMXImportAsync(System.Guid tmGuid)
        {
            return base.Channel.BeginChunkedTMXImportAsync(tmGuid);
        }
        
        public System.Guid BeginChunkedTMXImport2(System.Guid tmGuid, MQS.TM.TmxImportSettings settings)
        {
            return base.Channel.BeginChunkedTMXImport2(tmGuid, settings);
        }
        
        public System.Threading.Tasks.Task<System.Guid> BeginChunkedTMXImport2Async(System.Guid tmGuid, MQS.TM.TmxImportSettings settings)
        {
            return base.Channel.BeginChunkedTMXImport2Async(tmGuid, settings);
        }
        
        public void AddNextTMXChunk(System.Guid sessionId, byte[] tmxData)
        {
            base.Channel.AddNextTMXChunk(sessionId, tmxData);
        }
        
        public System.Threading.Tasks.Task AddNextTMXChunkAsync(System.Guid sessionId, byte[] tmxData)
        {
            return base.Channel.AddNextTMXChunkAsync(sessionId, tmxData);
        }
        
        public MQS.TM.TmxImportResult EndChunkedTMXImport(System.Guid sessionId)
        {
            return base.Channel.EndChunkedTMXImport(sessionId);
        }
        
        public System.Threading.Tasks.Task<MQS.TM.TmxImportResult> EndChunkedTMXImportAsync(System.Guid sessionId)
        {
            return base.Channel.EndChunkedTMXImportAsync(sessionId);
        }
        
        public System.Guid BeginChunkedTMXExport(System.Guid tmGuid)
        {
            return base.Channel.BeginChunkedTMXExport(tmGuid);
        }
        
        public System.Threading.Tasks.Task<System.Guid> BeginChunkedTMXExportAsync(System.Guid tmGuid)
        {
            return base.Channel.BeginChunkedTMXExportAsync(tmGuid);
        }
        
        public byte[] GetNextTMXChunk(System.Guid sessionId)
        {
            return base.Channel.GetNextTMXChunk(sessionId);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetNextTMXChunkAsync(System.Guid sessionId)
        {
            return base.Channel.GetNextTMXChunkAsync(sessionId);
        }
        
        public void EndChunkedTMXExport(System.Guid sessionId)
        {
            base.Channel.EndChunkedTMXExport(sessionId);
        }
        
        public System.Threading.Tasks.Task EndChunkedTMXExportAsync(System.Guid sessionId)
        {
            return base.Channel.EndChunkedTMXExportAsync(sessionId);
        }
        
        public string LookupSegment(string sessionId, string lookupDataXml, System.Guid tmGuid, MQS.TM.LookupSegmentRequest options)
        {
            return base.Channel.LookupSegment(sessionId, lookupDataXml, tmGuid, options);
        }
        
        public System.Threading.Tasks.Task<string> LookupSegmentAsync(string sessionId, string lookupDataXml, System.Guid tmGuid, MQS.TM.LookupSegmentRequest options)
        {
            return base.Channel.LookupSegmentAsync(sessionId, lookupDataXml, tmGuid, options);
        }
        
        public string Concordance(string sessionId, string searchExpression, System.Guid tmGuid, MQS.TM.ConcordanceRequest options)
        {
            return base.Channel.Concordance(sessionId, searchExpression, tmGuid, options);
        }
        
        public System.Threading.Tasks.Task<string> ConcordanceAsync(string sessionId, string searchExpression, System.Guid tmGuid, MQS.TM.ConcordanceRequest options)
        {
            return base.Channel.ConcordanceAsync(sessionId, searchExpression, tmGuid, options);
        }
        
        public void AddOrUpdateEntry(string sessionId, string segmentDataXml, System.Guid tmGuid)
        {
            base.Channel.AddOrUpdateEntry(sessionId, segmentDataXml, tmGuid);
        }
        
        public System.Threading.Tasks.Task AddOrUpdateEntryAsync(string sessionId, string segmentDataXml, System.Guid tmGuid)
        {
            return base.Channel.AddOrUpdateEntryAsync(sessionId, segmentDataXml, tmGuid);
        }
        
        public MQS.TM.ImportTMMetadataSchemeResultInfo ImportTMMetadataSchemeFromXML(System.Guid tmGuid, string scheme)
        {
            return base.Channel.ImportTMMetadataSchemeFromXML(tmGuid, scheme);
        }
        
        public System.Threading.Tasks.Task<MQS.TM.ImportTMMetadataSchemeResultInfo> ImportTMMetadataSchemeFromXMLAsync(System.Guid tmGuid, string scheme)
        {
            return base.Channel.ImportTMMetadataSchemeFromXMLAsync(tmGuid, scheme);
        }
    }
}
